name: highspecwindows tailscale

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install git -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: cài win và khởi chạy
        run: |
          git clone https://github.com/dockur/windows.git .
          docker build -t dockerd .
          docker run -i --name windows -p 8006:8006 --device=/dev/kvm -v  /mnt:/storage --cap-add NET_ADMIN --stop-timeout 99999990 dockerd
